### ISSUE TITLE
LIBRARIES missing

### ISSUE THREAD

**Issue by abufahad-1** [marshallamey/hydroponicAutomation#12]
hello my friend 
thank you for sharing your project

but I think same file are missing if I am not wrong

//LIBRARIES
  #include <SoftwareSerial.h>  
  #include <SPI.h>       
  #include <Adafruit_RGBLCDShield.h>
  #include <Wire.h>
  #include "RTClib.h"
  #include "DHT.h"  
  #include "Sensor.h"
  #include "Motor.h"

hope if you can explain this
I also wish if you add an explanation step by step to modify the settings

thanks and regards
Said

![hydroponic-automation](https://user-images.githubusercontent.com/44308057/47880984-4b738280-de3e-11e8-9e8f-13221dd38d8c.jpg)

**Comment by marshallamey** [comment]
Hello Said,
The Sensor and Motor libraries are the only ones that I personally wrote.  The rest were added using the Library Manager in the Arduino IDE.  Make sure to download each of those before running the program.  

It has been a long time since I have worked on this project but I will try and update it to make it more user friendly after I graduate this semester.  Thank you for trying it out.

[https://www.arduino.cc/en/Guide/Libraries](https://www.arduino.cc/en/Guide/Libraries)

**Comment by abufahad-1** [comment]
Hello my friend
I wish you success in your studies
I have a request if you can help me
If you can give me a list of libraries which you used in this project (The exact name or link to download)
I will be grateful to you to help me

Best Regards
Said

**Comment by marshallamey** [comment]
**SoftwareSerial is built-in.
SPI is built-in 
Wire is built-in**
Nothing to download here.

Download these others by going to "Manage Libraries" and searching for the following:
**Adafruit RGB LCD Shield Library** (by Adafruit)
**RTCLib** (by Adafruit)
**DHT Sensor Library** (by Adafruit)

Sensor.h and Motor.h are already in the repository.  I just verified and it compiled.  But you have to make sure the Board, Processor, and Port are set to the Arduino Mega 2560 for everything to work.  This code will not work on an Uno.

**Comment by abufahad-1** [comment]
Thanks my friend for follow-up and reply
I've done what you told me, but I got this Error:
Arduino: 1.8.7 (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"
In file included from C:\Users\said-\Documents\Arduino\libraries\DHT_sensor_library\DHT_U.cpp:22:0:
C:\Users\said-\Documents\Arduino\libraries\DHT_sensor_library\DHT_U.h:25:29: fatal error: Adafruit_Sensor.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
================================================
but the files is there 
![dht](https://user-images.githubusercontent.com/44308057/48693285-6b52c680-ebf2-11e8-9a7d-7925d256edda.jpg)
I'm using Arduino IDE 1.8.7 windows 10

**Comment by abufahad-1** [comment]
Solved it was version problem it must be v 1.2.2

**Comment by marshallamey** [comment]
Glad you figured it out.

Alternatively, you could also download the **Adafruit Unified Sensor** library (by Adafruit) if you want the most updated version of the DHT Sensor Library, which is 1.3.0 currently.

I'll close this issue, but let me know if you have any others.  Like I said, I'll start improving the documentation on this project after the year's end.
